export const products = [
  {
    id: 1,
    nameHe: 'מונסטרה',
    nameEn: 'Monstera Deliciosa',
    price: 120,
    image: '/images/shop-monstera.jpg',
    tags: ['צמחי בית', 'ענקים'],
    care: 1,
    isNew: false,
    gradient: 'linear-gradient(160deg,#1a3a1a 0%,#2D5A2D 100%)',
  },
  {
    id: 2,
    nameHe: 'פותוס',
    nameEn: 'Golden Pothos',
    price: 49,
    image: '/images/shop-pothos.jpg',
    tags: ['תלויים', 'קטנים'],
    care: 1,
    isNew: false,
    gradient: 'linear-gradient(160deg,#152A15 0%,#2D5A2D 100%)',
  },
  {
    id: 3,
    nameHe: 'פיקוס בנג׳מין',
    nameEn: 'Weeping Fig',
    price: 89,
    image: '/images/shop-fig.jpg',
    tags: ['צמחי בית', 'ענקים'],
    care: 2,
    isNew: false,
    gradient: 'linear-gradient(160deg,#1c3020 0%,#3a6a3a 100%)',
  },
  {
    id: 4,
    nameHe: 'זז',
    nameEn: 'ZZ Plant',
    price: 95,
    image: '/images/shop-zz.jpg',
    tags: ['עמידים'],
    care: 1,
    isNew: true,
    gradient: 'linear-gradient(160deg,#081008 0%,#1a2a1a 100%)',
  },
  {
    id: 5,
    nameHe: 'שרך',
    nameEn: 'Boston Fern',
    price: 49,
    image: '/images/shop-fern.jpg',
    tags: ['תלויים'],
    care: 2,
    isNew: false,
    gradient: 'linear-gradient(160deg,#2D5A2D 0%,#7A9E7A 100%)',
  },
  {
    id: 6,
    nameHe: 'עלה הפיל',
    nameEn: 'Elephant Ear',
    price: 120,
    image: '/images/shop-elephant.jpg',
    tags: ['ענקים'],
    care: 2,
    isNew: false,
    gradient: 'linear-gradient(160deg,#1a3a2a 0%,#2D5A2D 100%)',
  },
  {
    id: 7,
    nameHe: 'קקטוס מדברי',
    nameEn: 'Desert Cactus',
    price: 35,
    image: '/images/shop-cactus.jpg',
    tags: ['עמידים', 'קטנים'],
    care: 1,
    isNew: false,
    gradient: 'linear-gradient(160deg,#3a2a10 0%,#7A9E7A 100%)',
  },
  {
    id: 8,
    nameHe: 'פיקוס לירטה',
    nameEn: 'Fiddle Leaf Fig',
    price: 149,
    image: '/images/shop-fiddle.jpg',
    tags: ['ענקים', 'צמחי בית'],
    care: 3,
    isNew: true,
    gradient: 'linear-gradient(160deg,#152A15 0%,#2D5A2D 80%)',
  },
]

export const magazinePanels = [
  {
    id: 1,
    nameHe: 'הפיקוס בנג׳מין',
    nameEn: 'Weeping Fig',
    image: '/images/strip-fig.jpg',
    headlineHe: 'הירוק שממלא חדרים',
    headlineEn: 'The green that fills rooms',
    badge: 'פופולרי ביותר',
    gradient: 'radial-gradient(ellipse at 60% 40%,#1c3a1c 0%,#081008 70%)',
  },
  {
    id: 2,
    nameHe: 'שרך הנפרוליפיס',
    nameEn: 'Boston Fern',
    image: '/images/strip-fern.jpg',
    headlineHe: 'פרא ורך, ביחד.',
    headlineEn: 'Wild and soft, together.',
    badge: null,
    gradient: 'radial-gradient(ellipse at 40% 60%,#2D5A2D 0%,#081008 70%)',
  },
  {
    id: 3,
    nameHe: 'עלה הפיל',
    nameEn: 'Elephant Ear',
    image: '/images/strip-elephant.jpg',
    headlineHe: 'נוכחות שאי אפשר להתעלם ממנה',
    headlineEn: 'A presence you cannot ignore.',
    badge: null,
    gradient: 'radial-gradient(ellipse at 30% 70%,#1a3a20 0%,#081008 80%)',
  },
  {
    id: 4,
    nameHe: 'עציץ הקקטוס',
    nameEn: 'Desert Cactus Collection',
    image: '/images/strip-cactus.jpg',
    headlineHe: 'קצת מדבר, בתוך הבית.',
    headlineEn: 'A little desert, brought inside.',
    badge: null,
    gradient: 'radial-gradient(ellipse at 60% 40%,#3a2a10 0%,#081008 70%)',
  },
]

export const editorialFeatures = [
  {
    id: 1,
    label: 'CARE LEVEL · EASY',
    nameHe: 'המונסטרה שמשנה חדרים',
    nameEn: 'The plant that changes rooms',
    bodyHe: 'אחד הצמחים הנפוצים בעולם — ובצדק. עלים גדולים, צמיחה מרשימה, וטיפול שכל אחד יכול להרשות לעצמו. מספיק שעות אור, מים פעם בשבוע, והיא תתגמל אתכם.',
    price: 120,
    image: '/images/editorial-monstera.jpg',
    productId: 1,
    gradient: 'linear-gradient(135deg,#1a3a1a 0%,#081008 100%)',
    fullWidth: false,
  },
  {
    id: 2,
    label: 'CARE LEVEL · VERY EASY',
    nameHe: 'הצמח שסולח על הכל',
    nameEn: 'The plant that forgives everything',
    bodyHe: 'פותוס גדל בכל תנאי — מעט אור, מעט מים, מעט תשומת לב. מתאים לכל חלל, תולה בצורה מרהיבה, ומתרבה בקלות. הצמח הראשון שאנחנו ממליצים לכל מי שמתחיל.',
    price: 49,
    image: '/images/editorial-pothos.jpg',
    productId: 2,
    gradient: 'linear-gradient(135deg,#152A15 0%,#2D5A2D 100%)',
    fullWidth: false,
  },
  {
    id: 3,
    label: 'DROUGHT TOLERANT',
    nameHe: 'שורד. מתפתח. נראה מדהים.',
    nameEn: 'Survives. Thrives. Looks incredible.',
    bodyHe: 'הזז הוא הצמח של אנשים עסוקים. גדל לאיטו, אוהב צל, שורד שכחה. ועדיין — נראה כמו פסל.',
    price: 95,
    image: '/images/editorial-zz.jpg',
    productId: 4,
    gradient: 'linear-gradient(135deg,#081008 0%,#152A15 50%,#081008 100%)',
    fullWidth: true,
  },
]

export const careCards = [
  {
    id: 1,
    title: 'אור',
    image: '/images/care-light.jpg',
    headlineHe: 'צמחכם מחפש את השמש',
    bodyHe: 'רוב הצמחים לא צריכים שמש ישירה — הם צריכים אור בהיר ועקיף. מרחק של 1–2 מטר מחלון הוא הנקודה המושלמת לרוב הצמחים.',
    gradient: 'linear-gradient(135deg,#1a3a1a 0%,#2D5A2D 60%,#081008 100%)',
  },
  {
    id: 2,
    title: 'מים',
    image: '/images/care-water.jpg',
    headlineHe: 'פחות זה יותר, תמיד',
    bodyHe: 'הסיבה הנפוצה ביותר למות צמחים? השקיה יתר. לפני שמשקים — בדקו שהאדמה יבשה 2–3 ס"מ לעומק. תנו לה לנשום.',
    gradient: 'linear-gradient(135deg,#081008 0%,#1a3a2a 60%,#2D5A2D 100%)',
  },
  {
    id: 3,
    title: 'עציץ',
    image: '/images/care-pot.jpg',
    headlineHe: 'הכלי שמשנה הכל',
    bodyHe: 'לצמח צריך עציץ עם ניקוז. בלי חור בתחתית — מים נאספים בשורשים וגורמים לרקבון. זה הפרט שכולם מדלגים עליו.',
    gradient: 'linear-gradient(135deg,#2a1a08 0%,#3d2010 60%,#1a1008 100%)',
  },
]

export const galleryImages = [
  {
    id: 1,
    image: '/images/gallery-1.jpg',
    alt: 'מונסטרה בסלון תל אביבי מעוצב עם אור טבעי חם',
    gradient: 'linear-gradient(135deg,#1a3a1a 0%,#2D5A2D 100%)',
  },
  {
    id: 2,
    image: '/images/gallery-2.jpg',
    alt: 'פיקוס לירטה גדול ליד כורסת קריאה באור ערב זהוב',
    gradient: 'linear-gradient(160deg,#152A15 0%,#081008 100%)',
  },
  {
    id: 3,
    image: '/images/gallery-3.jpg',
    alt: 'אוסף סוקולנטים קטנים על אדן חלון מטבח מואר',
    gradient: 'linear-gradient(160deg,#2D5A2D 0%,#7A9E7A 100%)',
  },
  {
    id: 4,
    image: '/images/gallery-4.jpg',
    alt: 'זוג מטפח צמחי בית גדולים בסלון ירוק ומוארים',
    gradient: 'linear-gradient(135deg,#1c3020 0%,#2D5A2D 100%)',
  },
  {
    id: 5,
    image: '/images/gallery-5.jpg',
    alt: 'שולחן עבודה ביתי עם צמחים קטנים וספרים באור טבעי',
    gradient: 'linear-gradient(160deg,#3a3a20 0%,#7A9E7A 100%)',
  },
]
